
services:
  - type: web
    name: student-attendance-system
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input --clear && python manage.py migrate"
    startCommand: "gunicorn student_management_system.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DATABASE_URL
        fromDatabase:
          name: student_attendance_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: student_management_system.settings_production
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true

databases:
  - name: student_attendance_db
    plan: free
    databaseName: student_attendance
    user: student_attendance_user
