# Generated by Django 5.2.4 on 2025-08-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancereport',
            unique_together={('student_id', 'attendance_id')},
        ),
    ]
