# Generated by Django 5.1.6 on 2025-03-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_attendanceqrcode_session_year_alter_students_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceqrcode',
            name='allowed_radius',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='attendanceqrcode',
            name='teacher_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceqrcode',
            name='teacher_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='student_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='student_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
