# Generated by Django 5.1.6 on 2025-04-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_attendanceqrcode_allowed_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='student_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='verification_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
